@token = {{$dotenv TOKEN}}

POST http://localhost:3001/api/umas
content-type: application/json
Authorization: Bearer {{token}}
{
    "name": "Test",
    "hair_color": "Gris",
    "eye_color": "Gris",
    "height": "170",
    "avatar": "AvatarTest"
}